# golangci-lint configuration for Pythia
# Extremely strict configuration to enforce high code quality

run:
  timeout: 5m
  tests: true
  go: "1.23"
  allow-parallel-runners: true
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters-settings:
  cyclop:
    max-complexity: 12
    package-average: 8.0
    skip-tests: false

  gocyclo:
    min-complexity: 12

  gocognit:
    min-complexity: 15

  funlen:
    lines: 80
    statements: 50
    ignore-comments: true

  goconst:
    min-len: 3
    min-occurrences: 3
    ignore-tests: false

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - whyNoLint
      - hugeParam

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/jon/pythia

  gosimple:
    checks: ["all"]

  govet:
    enable-all: true
    disable:
      - fieldalignment

  lll:
    line-length: 120
    tab-width: 4

  maintidx:
    under: 20

  misspell:
    locale: US

  nakedret:
    max-func-lines: 30

  nestif:
    min-complexity: 4

  nilnil:
    checked-types:
      - ptr
      - func
      - iface
      - map
      - chan

  nolintlint:
    require-explanation: true
    require-specific: true

  prealloc:
    simple: true
    range-loops: true
    for-loops: true

  revive:
    ignore-generated-header: true
    severity: warning
    confidence: 0.8
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

  staticcheck:
    checks: ["all"]

  stylecheck:
    checks: ["all", "-ST1000", "-ST1003"]
    dot-import-whitelist: []
    http-status-code-whitelist: []

  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake
        yaml: snake
        xml: camel

  testpackage:
    skip-regexp: (export|internal)_test\.go

  unparam:
    check-exported: true

  unused:
    exported-fields-are-used: false
    local-variables-are-used: false

  whitespace:
    multi-if: true
    multi-func: true

  wsl:
    allow-assign-and-anything: false
    allow-assign-and-call: true
    allow-cuddle-declarations: false
    allow-multiline-assign: true
    allow-separated-leading-comment: false
    allow-trailing-comment: false
    force-case-trailing-whitespace: 0
    force-err-cuddling: false
    strict-append: true

linters:
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Additional strict linters
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - grouper
    - importas
    - interfacebloat
    - lll
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - tagliatelle
    - tenv
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
  disable:
    - depguard  # Too restrictive for this project
    - exhaustruct  # Not all structs need all fields
    - ginkgolinter  # Not using Ginkgo
    - gomnd  # Magic numbers are sometimes OK
    - ireturn  # Interfaces are fine to return
    - nlreturn  # Disabled due to conflicts
    - varnamelen  # Short names are OK in context

issues:
  exclude-use-default: false
  exclude-case-sensitive: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: false

  exclude-rules:
    # Test files can be more relaxed
    - path: _test\.go
      linters:
        - funlen
        - dupl
        - gochecknoglobals
        - gocognit
        - goconst
        - maintidx
        - wrapcheck
        - paralleltest
        - tparallel

    # Main can have init
    - path: main\.go
      linters:
        - gochecknoinits

    # Generated files
    - path: \.pb\.go
      linters:
        - all

    # Allow fmt.Errorf with %w
    - linters:
        - errorlint
      text: "non-wrapping format verb for fmt.Errorf"

severity:
  default-severity: error
  case-sensitive: false
  rules:
    - linters:
        - godox
      severity: warning
    - linters:
        - dupl
      severity: warning
