# GoReleaser configuration for Pythia
version: 2

project_name: pythia

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: pythia
    binary: pythia
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/jon/pythia/cmd/pythia.Version={{.Version}}
      - -X github.com/jon/pythia/cmd/pythia.Commit={{.Commit}}
      - -X github.com/jon/pythia/cmd/pythia.BuildDate={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: default
    formats:
      - tar.gz
      - zip
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - README.md
      - LICENSE
      - pythia.example.toml

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
  sort: asc
  abbrev: -1
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Security
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Performance
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: Others
      order: 999

release:
  github:
    owner: jon
    name: pythia
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Pythia {{ .Version }}

    AI-powered codebase analysis tool with MCP integration.
  footer: |
    ---

    **Full Changelog**: https://github.com/jon/pythia/compare/{{ .PreviousTag }}...{{ .Tag }}

    ### Installation

    ```bash
    # Homebrew (macOS/Linux)
    brew install jon/tap/pythia

    # Go
    go install github.com/jon/pythia@{{ .Tag }}

    # Docker
    docker pull ghcr.io/jon/pythia:{{ .Version }}
    ```

brews:
  - repository:
      owner: jon
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: https://github.com/jon/pythia
    description: AI-powered codebase analysis tool with MCP integration
    license: Apache-2.0
    skip_upload: auto
    test: |
      system "#{bin}/pythia", "version"
    install: |
      bin.install "pythia"

dockers:
  - image_templates:
      - "ghcr.io/jon/pythia:{{ .Version }}-amd64"
    dockerfile: deployments/docker/Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=Apache-2.0"
  - image_templates:
      - "ghcr.io/jon/pythia:{{ .Version }}-arm64"
    dockerfile: deployments/docker/Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/jon/pythia:{{ .Version }}"
    image_templates:
      - "ghcr.io/jon/pythia:{{ .Version }}-amd64"
      - "ghcr.io/jon/pythia:{{ .Version }}-arm64"
  - name_template: "ghcr.io/jon/pythia:latest"
    image_templates:
      - "ghcr.io/jon/pythia:{{ .Version }}-amd64"
      - "ghcr.io/jon/pythia:{{ .Version }}-arm64"

sboms:
  - artifacts: archive

signs:
  - cmd: cosign
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum
    output: true

docker_signs:
  - cmd: cosign
    artifacts: manifests
    output: true
    args:
      - "sign"
      - "${artifact}"
      - "--yes"
